import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

type CurrencyInformationProps = {
  name: string;
  ask: number;
  bid: number;
  arrow: number;
  ar_name: string;
  icon: string;
  change: number;
  change_percentage: number;
}

const Home: NextPage = () => {
  const currencyPrices = trpc.useQuery(["currency.getAllCurrencyPrices"]);

  return (
    <>
      <Head>
        <title>Adesh Alyoum</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
          <pre>
            <code className="text-gray-700">
              {currencyPrices.isLoading ?? (<>Loading prices</>)}
              {currencyPrices.data && (currencyPrices.data.map((currency: CurrencyInformationProps) => (CurrencyInformation(currency))))}
            </code>
          </pre>
        </div>
      </main>
    </>
  );
};

const CurrencyInformation = ({
  ar_name,
  ask,
  bid,
}: CurrencyInformationProps) => {
  return (
    <section className="flex justify-between bg-gray-300 border rounded-lg px-5 py-2 min-w-[500px] mb-3" dir="rtl">
      <div className="flex flex-col justify-center">
        <h2 className="text-lg text-gray-700 font-sans font-bold mb-2">{ar_name}</h2>
        <p className="text-sm text-gray-600 font-sans">شراء: {ask}</p>
        <p className="text-sm text-gray-600 font-sans">بيع: {bid}</p>
      </div>
    </section>
  )
}

export default Home;
