import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import Script from "next/script";
import { useEffect } from "react";
import { trpc } from "../utils/trpc";

type CurrencyInformationProps = {
  name: string;
  ask: number;
  bid: number;
  arrow: number;
  ar_name: string;
  icon: string;
  change: number;
  change_percentage: number;
}



const countryISO3166 = {
  USD: "US",
  EUR: "EU",
  TRY: "TR",
  EGP: "EG",
  SAR: "SA",
  JOD: "JO",
  AED: "AE",
  QAR: "QA",
  BHD: "BH",
  LYD: "LY",
  KWD: "KW",
  OMR: "OM",
  GBP: "GB",
  SEK: "SE",
  CAD: "CA",
  NOK: "NO",
  DKK: "DK",
}


declare var adsbygoogle: any;

const Home: NextPage = () => {
  const currencyPrices = trpc.useQuery(["currency.getAllCurrencyPrices"]);
  useEffect(() => {
    var ads = document.getElementsByClassName("adsbygoogle").length;
    for (var i = 0; i < ads; i++) {
      try {
        (adsbygoogle = (window as any).adsbygoogle || []).push({});
      } catch (e) { }
    }
  }, []);


  return (
    <div className="bg-[#fdc40a] antialiased h-screen overflow-y-auto font-cairo">
      <Head>
        <title>Adesh Alyoum</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Cairo&display=swap" rel="stylesheet"></link>
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5058823701024243"
          crossOrigin="anonymous"></script>
      </Head>

      <header>
        <ins className="adsbygoogle block"
          data-ad-client="ca-pub-5058823701024243"
          data-ad-slot="3357486343"
          data-ad-format="auto"
          data-full-width-responsive="true">

        </ins>
      </header>
      <main >
        <div className="grid gap-3 p-2 mx-auto max-w-[500px]">

          {currencyPrices.isLoading ?? (<>Loading prices</>)}
          {currencyPrices.data && (currencyPrices.data.map((currency: CurrencyInformationProps) => (CurrencyInformation(currency))))}

        </div>
      </main>
    </div>
  );
};

const CurrencyInformation = ({
  ar_name,
  name,
  ask,
  bid,
}: CurrencyInformationProps) => {
  const currency = `${name[0]}${name[1]}`.toLowerCase();
  return (
    <section className="flex justify-between bg-white border rounded-lg relative rounded-l-full overflow-hidden" dir="rtl" key={name}>
      <div className="flex flex-col justify-center px-5 py-2">
        <h2 className="text-lg text-gray-700  font-bold mb-2">{ar_name}</h2>
        <p className="text-sm text-gray-600 ">شراء: {ask}</p>
        <p className="text-sm text-gray-600 ">بيع: {bid}</p>
      </div>
      <img src={`https://flagcdn.com/${currency}.svg`} alt="Country flag" className="object-cover h-full max-w-[140px]" />
    </section>
  )
}

export default Home;
